# Generated by Django 4.1 on 2024-05-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("frontlinks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                ("cropId", models.AutoField(primary_key=True, serialize=False)),
                ("cropName", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pest",
            fields=[
                ("pestId", models.AutoField(primary_key=True, serialize=False)),
                ("pestName", models.CharField(max_length=100)),
                ("pestImage", models.URLField()),
                ("pestInfo", models.JSONField()),
                ("pestStepImage1", models.URLField()),
                ("pestStepImage2", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pesticide",
            fields=[
                ("pesticideId", models.AutoField(primary_key=True, serialize=False)),
                ("pesticideName", models.CharField(max_length=100)),
                ("pesticideInfo", models.TextField()),
                ("pesticideExcel", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiskForecast",
            fields=[
                ("riskForecastId", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("percentage", models.FloatField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontlinks.location",
                    ),
                ),
                (
                    "pest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predictors.pest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PestPesticide",
            fields=[
                (
                    "pestPesticideId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "pest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predictors.pest",
                    ),
                ),
                (
                    "pesticide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predictors.pesticide",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Management",
            fields=[
                ("managementId", models.AutoField(primary_key=True, serialize=False)),
                ("management1", models.TextField()),
                ("management2", models.TextField(blank=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predictors.crop",
                    ),
                ),
                (
                    "pest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predictors.pest",
                    ),
                ),
                (
                    "pesticide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predictors.pesticide",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropPesticide",
            fields=[
                (
                    "cropPesticideId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predictors.crop",
                    ),
                ),
                (
                    "pesticide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predictors.pesticide",
                    ),
                ),
            ],
        ),
    ]
