# Generated by Django 4.1 on 2024-05-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("predictors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("locationId", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="riskforecast",
            name="riskLevel",
            field=models.CharField(default="괜찮", max_length=50),
        ),
        migrations.AlterField(
            model_name="riskforecast",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="predictors.location"
            ),
        ),
    ]
