# Generated by Django 4.1 on 2024-05-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predictors", "0002_location_riskforecast_risklevel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskforecast",
            name="percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="riskforecast",
            name="riskLevel",
            field=models.CharField(default="디폴트", max_length=50),
        ),
    ]
