# Generated by Django 4.1 on 2024-05-22 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("predictors", "0003_alter_riskforecast_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskforecast",
            name="pest",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="predictors.pest",
            ),
        ),
    ]
