# Generated by Django 4.1 on 2024-05-31 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("predictors", "0004_alter_riskforecast_pest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riskforecast",
            name="location",
        ),
        migrations.AlterField(
            model_name="pest",
            name="pestImage",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="pest",
            name="pestStepImage1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="pest",
            name="pestStepImage2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="riskforecast",
            name="percentage",
            field=models.IntegerField(default=999),
        ),
        migrations.CreateModel(
            name="UserSelect",
            fields=[
                ("userSelectId", models.AutoField(primary_key=True, serialize=False)),
                ("selectedCrop", models.CharField(max_length=100)),
                ("selectedLocation", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="riskforecast",
            name="selectedCrop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_crop_forecasts",
                to="predictors.userselect",
            ),
        ),
        migrations.AddField(
            model_name="riskforecast",
            name="selectedLocation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_location_forecasts",
                to="predictors.userselect",
            ),
        ),
    ]
