# Generated by Django 4.1 on 2024-05-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "predictors",
            "0005_remove_riskforecast_location_alter_pest_pestimage_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riskforecast",
            name="date",
        ),
        migrations.AddField(
            model_name="userselect",
            name="selectedDate",
            field=models.DateField(default='2024-02-29'),
            preserve_default=False,
        ),
    ]
