# Generated by Django 4.1 on 2024-05-31 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("predictors", "0006_remove_riskforecast_date_userselect_selecteddate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="riskforecast",
            old_name="percentage",
            new_name="percentages",
        ),
        migrations.RenameField(
            model_name="riskforecast",
            old_name="riskLevel",
            new_name="riskLevels",
        ),
    ]
