# Generated by Django 4.1 on 2024-06-02 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("predictors", "0010_alter_pesticide_pesticideexcel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="management",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="management",
            name="pesticide",
        ),
    ]
