# Generated by Django 4.1 on 2024-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predictors", "0011_remove_management_crop_remove_management_pesticide"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pesticide",
            name="pesticideInfo",
        ),
        migrations.AddField(
            model_name="pesticide",
            name="companyName",
            field=models.CharField(default="회사", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pesticide",
            name="safeUsageFrequency",
            field=models.CharField(default="수확 며칠 전?", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pesticide",
            name="safeUsagePeriod",
            field=models.CharField(default="2회", max_length=100),
            preserve_default=False,
        ),
    ]
