# Generated by Django 4.1 on 2024-06-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "predictors",
            "0012_remove_pesticide_pesticideinfo_pesticide_companyname_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pest",
            name="pestStepImage3",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
