# Generated by Django 4.1 on 2024-06-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0013_pest_peststepimage3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userselect',
            options={'get_latest_by': 'userSelectId'},
        ),
    ]
