# Generated by Django 4.1 on 2024-06-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0014_alter_userselect_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pest',
            name='pestInfo',
            field=models.TextField(),
        ),
    ]
