# Generated by Django 4.1 on 2024-05-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("nickname", models.CharField(max_length=50)),
                ("ageRange", models.CharField(max_length=20)),
                ("nationality", models.CharField(max_length=50)),
            ],
        ),
    ]
