# Generated by Django 4.1 on 2024-05-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("locationId", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
