# Generated by Django 4.1 on 2024-05-21 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("predictors", "0002_location_riskforecast_risklevel_and_more"),
        ("frontlinks", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
